#!/usr/bin/env bash
# configures Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update -y
sudo apt-get install nginx -y

sudo ufw allow "Nginx HTTP"

sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/bradley-mwangangi permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
