#!/usr/bin/env bash
# install and configure HAproxy on load balancer server

sudo apt-get -y update
sudo apt-get -y install haproxy

config="
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 326136-web-01 34.229.189.37 check port 80
        server 326136-web-02 3.89.160.195 check port 80
"
echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
