#!/usr/bin/env bash
# finding out what’s keeping Ubuntu container’s Nginx installation from
# listening on port 80, then automating a fix 

sudo sed -i "s/ipv6only=on//" /etc/nginx/sites-available/default
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
